#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/{keys,php,www} \
    /config/log/{nginx,php} \
    /config/nginx/site-confs \
    /config/nginx/lua \
    /config/lua \
