name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build L1 image
      run: docker build -t openresty-base -f L1-openresty-base/Dockerfile .

    - name: Build L2 image
      run: docker build -t openresty-base-fat --build-arg L1_IMAGE=openresty-base -f L2-openresty-fat/Dockerfile .

    - name: Build final image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lscr_openresty:$(date +%s) --build-arg L2_IMAGE=openresty-base-fat .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lscr_openresty:$(date +%s) 
